name: curl-simosx
version: '7.65'
summary: CLI tool for transferring data with URL syntax (HTTP, HTTPS, etc)
description: |
    A command line tool and library for transferring data with URL syntax, 
    supporting HTTP, HTTPS, FTP, FTPS, GOPHER, TFTP, SCP, SFTP, SMB, TELNET, 
    DICT, LDAP, LDAPS, FILE, IMAP, SMTP, POP3, RTSP and RTMP. 
    libcurl offers a myriad of powerful features

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps: 
  curl:
    command: bin/curl
    plugs:
      - network

parts:
  curl: 
    plugin: autotools
    source: https://github.com/curl/curl.git
    source-tag: curl-7_65_0
    build-packages:
      - libssl-dev
      - libssh-dev
      - zlib1g-dev 
      - libbrotli-dev
      - libidn11-dev 
      - librtmp-dev
      - libldap2-dev
    stage-packages:
      - libasn1-8-heimdal
      - libbrotli1
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libidn2-0
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssl1.0.0
      - libwind0-heimdal

